# Generated by Django 3.2.19 on 2023-06-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_available', models.BooleanField(default=True)),
                ('battery_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charging_speed', models.DecimalField(choices=[('Level 1', 2.3), ('Level 2', 9), ('DC Fast Charging', 60)], decimal_places=2, max_digits=5)),
                ('solar_panel_capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solar_intensity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solar_panel_efficiency', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Guest', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('energy_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chargingstation')),
            ],
        ),
    ]
