# Generated by Django 3.2.19 on 2023-06-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230612_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='is_fuctional',
            new_name='is_functional',
        ),
        migrations.RenameField(
            model_name='chargingstation',
            old_name='solar_intensity',
            new_name='solar_irradiance',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='usage_cost',
            field=models.FloatField(default=0, help_text='Cost per Kwh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='charging_speed',
            field=models.DecimalField(choices=[('Level 1', 2.3), ('Level 2', 9), ('DC Fast Charging', 60)], decimal_places=2, default=60, help_text='level 1,level2 or fast charging', max_digits=5),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='solar_panel_efficiency',
            field=models.DecimalField(decimal_places=2, default=22, help_text='Standard', max_digits=4),
        ),
    ]
