# Generated by Django 3.2.19 on 2023-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230613_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='stationid',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
